dist: trusty
sudo: false
language: python
python: "2.7"
install:
    - pip install -U pip setuptools wheel
    - pip install -U pytest
    - pip install -e .
script:
    - py.test --cov-config .coveragerc --cov=wwb_scanner
after_success:
    - coveralls
